// Generated by gencpp from file franka_msgs/SetJointConfiguration.msg
// DO NOT EDIT!


#ifndef FRANKA_MSGS_MESSAGE_SETJOINTCONFIGURATION_H
#define FRANKA_MSGS_MESSAGE_SETJOINTCONFIGURATION_H

#include <ros/service_traits.h>


#include <franka_msgs/SetJointConfigurationRequest.h>
#include <franka_msgs/SetJointConfigurationResponse.h>


namespace franka_msgs
{

struct SetJointConfiguration
{

typedef SetJointConfigurationRequest Request;
typedef SetJointConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointConfiguration
} // namespace franka_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::franka_msgs::SetJointConfiguration > {
  static const char* value()
  {
    return "772aebee560c498b58210c453ba3c24c";
  }

  static const char* value(const ::franka_msgs::SetJointConfiguration&) { return value(); }
};

template<>
struct DataType< ::franka_msgs::SetJointConfiguration > {
  static const char* value()
  {
    return "franka_msgs/SetJointConfiguration";
  }

  static const char* value(const ::franka_msgs::SetJointConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::franka_msgs::SetJointConfigurationRequest> should match
// service_traits::MD5Sum< ::franka_msgs::SetJointConfiguration >
template<>
struct MD5Sum< ::franka_msgs::SetJointConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetJointConfiguration >::value();
  }
  static const char* value(const ::franka_msgs::SetJointConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetJointConfigurationRequest> should match
// service_traits::DataType< ::franka_msgs::SetJointConfiguration >
template<>
struct DataType< ::franka_msgs::SetJointConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetJointConfiguration >::value();
  }
  static const char* value(const ::franka_msgs::SetJointConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::franka_msgs::SetJointConfigurationResponse> should match
// service_traits::MD5Sum< ::franka_msgs::SetJointConfiguration >
template<>
struct MD5Sum< ::franka_msgs::SetJointConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::franka_msgs::SetJointConfiguration >::value();
  }
  static const char* value(const ::franka_msgs::SetJointConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::franka_msgs::SetJointConfigurationResponse> should match
// service_traits::DataType< ::franka_msgs::SetJointConfiguration >
template<>
struct DataType< ::franka_msgs::SetJointConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::franka_msgs::SetJointConfiguration >::value();
  }
  static const char* value(const ::franka_msgs::SetJointConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FRANKA_MSGS_MESSAGE_SETJOINTCONFIGURATION_H
