# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

default_velocity_scaling_factor: 0.2
default_acceleration_scaling_factor: 0.2

joint_limits:
  panda_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  panda_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0

  panda_joint1:
    has_position_limits: true
    min_position: -2.7
    max_position: 2.7
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

  panda_joint2:
    has_position_limits: true
    min_position: -1.5
    max_position: 1.5
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

  panda_joint3:
    has_position_limits: true
    min_position: -2.7
    max_position: 2.7
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

  panda_joint4:
    has_position_limits: true
    min_position: -2.8
    max_position: -0.2
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

  panda_joint5:
    has_position_limits: true
    min_position: -2.7
    max_position: 2.7
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

  panda_joint6:
    has_position_limits: true
    min_position: 0.0
    max_position: 3.5
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

  panda_joint7:
    has_position_limits: true
    min_position: -2.7
    max_position: 2.7
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 0.2

